### ISSUE TITLE
Deprecation of ```np.long`` in NumPy 1.20 in .merge() method

### ISSUE THREAD

**Issue by homonecloco** [biocore-ntnu/pyranges#258]
Hi, 

I'm using  ```pyranges-0.0.115``` with ```NumPy-1.22.2``` and ```pandas-1.4.0```. When calling the method range I get the following warning.  

```
.venv/lib/python3.9/site-packages/pyranges/methods/merge.py:16: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  starts, ends, number = find_clusters(cdf.Start.values, cdf.End.values, slack)
```

I thought you may want to be aware of this change. 
Best, 
Ricardo.

**Comment by endrebak** [comment]
Thanks, it will be supported for a long time, but this is something I should get around to fixing anyways.

Sorry for the late reply, was not notified of your post.

**Comment by DongzeHE** [comment]
Hi,

I use `pyranges` in my [function](https://github.com/COMBINE-lab/pyroe/blob/main/src/pyroe/make_splici_txome.py). As this warning keeps showing when I run `pytest`, I sincerely hope you can fix it. Thank you.

- Dongze

**Comment by endrebak** [comment]
I'll try to do so tomorrow :)

**Comment by DongzeHE** [comment]
Great! Thanks so much! Here are the warnings I got. Hope it will help you locate the places to change.

```
  /home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages/pyranges/methods/merge.py:71: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    ids, starts, ends, number = merge_by(cdf.Start.values, cdf.End.values, cdf.ClusterBy.values, slack)

tests/test_make_splici.py::test_make_splici
tests/test_make_splici.py::test_make_splici
  /home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages/pyranges/genomicfeatures.py:569: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    exons.End.values, exon_ids.values)
```

**Comment by endrebak** [comment]
I am looking at it now. It is actually a problem in the pyranges support libraries I wrote.

**Comment by endrebak** [comment]
I've updated sorted_nearest, ncls, and pyrle to not use np.long anymore. Can you try updating those Python libraries and see if the issue is fixed?

**Comment by DongzeHE** [comment]
Hi @endrebak,

There were errors reported by gcc((Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0) when I install the packages you mentioned.  If possible, could you also update them in conda? thanks!

```$ pip install sorted_nearest
Collecting sorted_nearest
  Using cached sorted_nearest-0.0.35.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cython in /home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages (from sorted_nearest) (0.29.30)
Requirement already satisfied: numpy in /home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages (from sorted_nearest) (1.21.6)
Building wheels for collected packages: sorted_nearest
  Building wheel for sorted_nearest (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for sorted_nearest (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/sorted_nearest
      copying sorted_nearest/__init__.py -> build/lib.linux-x86_64-cpython-37/sorted_nearest
      copying sorted_nearest/version.py -> build/lib.linux-x86_64-cpython-37/sorted_nearest
      creating build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/__init__.py -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/introns.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/annotate_clusters.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/k_nearest_ties.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/max_disjoint_intervals.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/sorted_nearest.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/tiles.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/windows.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/k_nearest.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/merge_by.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/cluster_by.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/clusters.pyx -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/csorted_nearest.pxd -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/utarray.h -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/clusters.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/cluster_by.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/introns.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/annotate_clusters.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/k_nearest_ties.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/sorted_nearest.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/k_nearest.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/tiles.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/merge_by.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/max_disjoint_intervals.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      copying sorted_nearest/src/windows.c -> build/lib.linux-x86_64-cpython-37/sorted_nearest/src
      running build_ext
      building 'sorted_nearest.src.sorted_nearest' extension
      creating build/temp.linux-x86_64-cpython-37
      creating build/temp.linux-x86_64-cpython-37/sorted_nearest
      creating build/temp.linux-x86_64-cpython-37/sorted_nearest/src
      gcc -pthread -B /home/zaza/miniconda3/envs/pyroe/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/zaza/bin/zlib/include -I/home/linuxbrew/.linuxbrew/include -fPIC -I. -I/home/zaza/miniconda3/envs/pyroe/include/python3.7m -c sorted_nearest/src/sorted_nearest.c -o build/temp.linux-x86_64-cpython-37/sorted_nearest/src/sorted_nearest.o
      gcc -pthread -shared -B /home/zaza/miniconda3/envs/pyroe/compiler_compat -L/home/zaza/miniconda3/envs/pyroe/lib -Wl,-rpath=/home/zaza/miniconda3/envs/pyroe/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L/home/zaza/bin/zlib/lib -L/home/linuxbrew/.linuxbrew/lib -I/home/zaza/bin/zlib/include -I/home/linuxbrew/.linuxbrew/include build/temp.linux-x86_64-cpython-37/sorted_nearest/src/sorted_nearest.o -o build/lib.linux-x86_64-cpython-37/sorted_nearest/src/sorted_nearest.cpython-37m-x86_64-linux-gnu.so
      /home/zaza/miniconda3/envs/pyroe/compiler_compat/ld: cannot find /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sorted_nearest
Failed to build sorted_nearest
ERROR: Could not build wheels for sorted_nearest, which is required to install pyproject.toml-based projects```

**Comment by endrebak** [comment]
But the packages should be automatically updated in conda by the conda-bot?

**Comment by endrebak** [comment]
I think it was not updated in conda due to a bug in sorted_nearest. Fixing

**Comment by ivargr** [comment]
Am I correct that this still is an issue?

As far as I can see, sorted_nearest is still using `np.long` here: https://github.com/pyranges/sorted_nearest/blob/master/sorted_nearest/src/clusters.pyx#L11

I get this problem when using pyranges version 0.0.120 from conda.

**Comment by endrebak** [comment]
I haven't looked at the pyranges-supporting libraries. I'll do so tomorrow!
Thanks for reminding me.

**Comment by cmatKhan** [comment]
This seems to be causing an error for me. Confusing b/c this was working until this evening...I did update my environment, so * may have * updated pyranges. I am currently using `0.0.120`

```raw
concat_ranges
+--------------+-------------------+--------------+-----------+-------+
| Chromosome   | Source            | Feature      | Start     | +6    |
| (category)   | (object)          | (category)   | (int32)   | ...   |
|--------------+-------------------+--------------+-----------+-------|
| chr1         | hg002_sqanti_fltr | transcript   | 1013503   | ...   |
| chr1         | hg002_sqanti_fltr | transcript   | 1053929   | ...   |
| chr1         | hg002_sqanti_fltr | transcript   | 1308594   | ...   |
| chr1         | hg004_sqanti_fltr | transcript   | 1013496   | ...   |
| ...          | ...               | ...          | ...       | ...   |
| chr1         | hg005_sqanti_fltr | transcript   | 1211340   | ...   |
| chr1         | hg005_sqanti_fltr | transcript   | 1216908   | ...   |
| chr1         | hg005_sqanti_fltr | transcript   | 1216914   | ...   |
| chr1         | hg005_sqanti_fltr | transcript   | 1253914   | ...   |
+--------------+-------------------+--------------+-----------+-------+
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oguzkhan/code/isocomp/.venv/lib/python3.9/site-packages/pyranges/pyranges.py", line 1145, in cluster
    df = pyrange_apply_single(_cluster, self, **kwargs)
  File "/home/oguzkhan/code/isocomp/.venv/lib/python3.9/site-packages/pyranges/multithreaded.py", line 348, in pyrange_apply_single
    result = call_f_single(function, nparams, df, **kwargs)
  File "/home/oguzkhan/code/isocomp/.venv/lib/python3.9/site-packages/pyranges/multithreaded.py", line 31, in call_f_single
    return f.remote(df, **kwargs)
  File "/home/oguzkhan/code/isocomp/.venv/lib/python3.9/site-packages/pyranges/methods/cluster.py", line 14, in _cluster
    ids = annotate_clusters(cdf.Start.values, cdf.End.values, slack)
  File "sorted_nearest/src/annotate_clusters.pyx", line 10, in sorted_nearest.src.annotate_clusters.annotate_clusters
  File "/home/oguzkhan/code/isocomp/.venv/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'long'
```

the pyranges obj is attached:

[concat_ranges.gtf.gz](https://github.com/biocore-ntnu/pyranges/files/10305242/concat_ranges.gtf.gz)

**Comment by cmatKhan** [comment]
looks like this is causing problems elsewhere, including at NASA:

https://github.com/nasa/puma/issues/9#issuecomment-1368069775

downgrading from numpy `1.24` to `1.23` resolved this error. But, this issue should stay open and get fixed.

**Comment by endrebak** [comment]
Looking at it now, thanks!

**Comment by endrebak** [comment]
I've updated sorted_nearest: https://github.com/pyranges/sorted_nearest/blob/master/CHANGELOG

PyPI version should be working now, bioconda in a few hours.

**Comment by zdk123** [comment]
Fyi, bioconda seems stuck on v0.0.37
![image](https://user-images.githubusercontent.com/2637124/221961593-28bba356-0825-4beb-adca-a7ee7e62bdf6.png)

**Comment by marco-mariotti** [comment]
This issue is still present, as bioconda installs version 0.0.3 of sorted_nearest.
As consequence, today on a clean pyranges installation, some methods fail, e.g. _max_disjoint_
